# SPDX-FileCopyrightText: 2026 Hari Srinivasan <harisrini21@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-only

"""Lock file generation with integrity hashes for agent versions."""

import hashlib
from datetime import UTC, datetime

import yaml
from loguru import logger


def compute_integrity_hash(content: str) -> str:
    """Compute sha256 integrity hash for lock file entries."""
    logger.debug("compute_integrity_hash: len={}", len(content))
    digest = hashlib.sha256(content.encode()).hexdigest()
    return f"sha256-{digest}"


def generate_lock_file(
    resolved_components: list[dict],
) -> str:
    """Generate observal-agent.lock YAML content with integrity hashes.

    Args:
        resolved_components: list of dicts with keys:
            - type: str (mcp, skill, hook, prompt, sandbox)
            - name: str
            - resolved: str (version string)
            - id: str (component UUID)
            - source_sha: str | None (for external components)
            - content: str | None (for inline components — used to compute integrity)

    Returns:
        YAML string for observal-agent.lock
    """
    logger.debug("generate_lock_file: resolved_components={}", resolved_components)
    entries = []
    for comp in resolved_components:
        entry = {
            "type": comp["type"],
            "name": comp["name"],
            "resolved": comp["resolved"],
            "id": comp["id"],
        }
        if comp.get("source_sha"):
            entry["source_sha"] = comp["source_sha"]
        if comp.get("content"):
            entry["integrity"] = compute_integrity_hash(comp["content"])
        entries.append(entry)

    lock_data = {
        "lock_version": 1,
        "resolved_at": datetime.now(UTC).isoformat(),
        "components": entries,
    }

    header = "# Auto-generated by observal agent release — do not edit manually\n"
    return header + yaml.dump(lock_data, default_flow_style=False, sort_keys=False)
